-- create database materiadbpia
use materiadbpia

INSERT INTO roles (nombre, permisosAdmn) VALUES ('Administrador', 1)
INSERT INTO roles (nombre, permisosAdmn) VALUES ('Usuario', 0)

INSERT INTO dependencias (nombre) VALUES ('FCFM')
INSERT INTO dependencias (nombre) VALUES ('FARQ')
INSERT INTO dependencias (nombre) VALUES ('FIME')
INSERT INTO dependencias (nombre) VALUES ('FACPYA')
INSERT INTO dependencias (nombre) VALUES ('FCB')

INSERT INTO sedes (nombre, ubicacion, capacidad) VALUES ('Auditorio 1', 'Planta baja', 100)
INSERT INTO sedes (nombre, ubicacion, capacidad) VALUES ('Auditorio 2', 'Primer piso', 75)
INSERT INTO sedes (nombre, ubicacion, capacidad) VALUES ('Plaza cultural', 'Planta baja', 300)
INSERT INTO sedes (nombre, ubicacion, capacidad) VALUES ('Laboratorio', 'Segundo piso', 35)

INSERT INTO invitados (nombre) VALUES ('Tomasa Palma')
INSERT INTO invitados (nombre) VALUES ('Karima Rosell')
INSERT INTO invitados (nombre) VALUES ('Santos Farina')

INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Sergi Zheng', 1234567, '2$&2xcJ', 1, 2)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Yeray Bastida', 5124561, '!@nBu4M', 2, 2)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Vicente Jose Martinez', 1536568, 'B!aJ3i!', 3, 1)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Maria Asuncion Villaverde', 6653568, '2Q8S*^z', 4, 2)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Jaime Prados', 7134561, 'r$WB&h5', 5, 2)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Esteban Pujol', 8653563, 'Z92wM@*', 1, 2)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Judit Rebollo', 9503562, '@5%fK92', 2, 2)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Blanca Arroyo', 2368203, 'Vt2Cb!^', 3, 1)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Anais Saavedra', 1384570, '*BV!fA6', 4, 1)
INSERT INTO usuarios (nombre, matricula, contraseña, idDependencia, idRoles)
VALUES ('Sonia Maria Blazquez', 4089271, '&3^uGL2', 5, 2)

-- Considera que en la fecha esta YYYYMMDD HH:MM de acuerdo a
-- https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver16
INSERT INTO eventos (nombre, fecha, idSedes, idDependencias)
VALUES ('Orquesta Sinfonica #23', '20221210 15:30:00', 3, 2)
INSERT INTO eventos (nombre, fecha, idSedes, idDependencias)
VALUES ('Orquesta Sinfonica #24', '20231210 15:45:00', 3, 2)
INSERT INTO eventos (nombre, fecha, idSedes, idDependencias)
VALUES ('Confrencia Mate Salud', '20231101 08:15:00', 1, 1)
INSERT INTO eventos (nombre, fecha, idSedes, idDependencias)
VALUES ('Exposicion Robotica #1', '20231128 18:00:00', 4, 3)

-- Los valores de idEventos pueden cambiar ya que en la base de datos actual,
-- no existen los campos 3, 5, 6, 7, 8 por errores en la base de datos local
INSERT INTO asistenciaInvitados (asistencia, idInvitados, idEventos) VALUES  (1, 1, 1)
INSERT INTO asistenciaInvitados (asistencia, idInvitados, idEventos) VALUES  (1, 2, 1)
INSERT INTO asistenciaInvitados (asistencia, idInvitados, idEventos) VALUES  (0, 1, 2)
INSERT INTO asistenciaInvitados (asistencia, idInvitados, idEventos) VALUES  (1, 2, 2)
INSERT INTO asistenciaInvitados (asistencia, idInvitados, idEventos) VALUES  (1, 3, 2)
INSERT INTO asistenciaInvitados (asistencia, idInvitados, idEventos) VALUES  (1, 2, 4)
INSERT INTO asistenciaInvitados (asistencia, idInvitados, idEventos) VALUES  (1, 3, 4)
INSERT INTO asistenciaInvitados (asistencia, idInvitados, idEventos) VALUES  (0, 3, 9)

INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (15125212, 0, 1, 1)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (13225212, 0, 2, 1)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (15122312, 0, 5, 1)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (15658522, 0, 6, 1)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (15138959, 0, 8, 1)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (24726212, 0, 1, 2)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (32727212, 0, 2, 2)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (23525312, 0, 3, 2)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (10032502, 0, 4, 2)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (15474759, 0, 5, 2)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (54737352, 0, 6, 2)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (15265462, 0, 7, 2)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (24624639, 0, 9, 2)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (57324639, 150, 1, 4)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (86824639, 150, 6, 4)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (97724639, 150, 8, 4)
INSERT INTO boletos (codigoBarras, costo, idUsuarios, idEventos) VALUES (11114634, 370, 3, 9)